### ISSUE TITLE
Forward and reverse output

### ISSUE THREAD

**Issue by miketaormina** [AllenNeuralDynamics/aind-ccf-registration#12]
https://github.com/AllenNeuralDynamics/aind-ccf-registration/blob/8d3812f1193a3dc14e6ca7d3aa533071b9e10257/code/aind_ccf_reg/register.py#L287

In the current CCF registration code, we are defining the Allen CCF template to be the "fixed" image and the (downsampled) SmartSPIM data as the "moving" image. ANTs then computes (amongst other things):
- forward transform (`fwdtransforms`: Transforms to move from moving to fixed image.)
- inverse transform (`invtransforms`: Transforms to move from fixed to moving image.)
These definitions (from [ANTsPy](https://github.com/ANTsX/ANTsPy/blob/master/ants/registration/interface.py#L155)) are confusing to read - so many "moves."
We use the "SyN" type of transform, so each of these have an affine + deformable component

The current registration code outputs:
- `fwdtransforms[1]` to the `affine_transforms_file`
- `invtransforms[1]` to the `warp_transforms_file`
This is a bit weird, saving one component from each transform, but not all components from either. I guess it works for the quantification capsule because the affine gets inverted there (I think I can see that in the quantification capsule, but I don't have repo access so I can't link here. It's on `quantification.py line 82`).
*aside: I don't really understand why the `fixed -> moving` transform (inverse) deformation field correctly moves points from the original data space into the CCF...*

The reason I bring this to the attention of the group is to advocate storing both forward and reverse transforms.
It may be useful, for example, to see the original high resolution data with the CCF boundaries present.
At the moment, this would require moving the full resolution image into CCF space (or at least a higher resolution version of it).
With the complete transform, you could transform a specific annotated region mask into the raw data space, then look at cell segmentation, counting, etc. in the raw data. I admit that this may be an edge case.

**Suggested Changes**
Either:
1. Output the affine and warp transforms from the same (I guess inverse??? but seems like it should be forward) transform that will allow transforming original data into CCF space. This is just a more consistent version of what is happening, I think. This would be a choice to enforce always working in CCF space. *aside: can we save the whole transform in one file and apply it in one step?*
2. Output both components of both forward and reverse transforms for completeness. These are both already computed, so the only reason not to do this is if the displacement array occupies a lot of disk space.

Let me tag @camilolaiton and @sharmishtaa , since I know they both work on registration.

**Comment by miketaormina** [comment]
I spoke with Nick today and learned why this is weird and why it works anyway. It sounds like the ANTs package has a bug in the displacement fields such that the forward transform field is returned in both the forward and reverse results. So the fact that the inverse field works to bring the cell locations into CCF space is because it is actually the forward displacement field.

Seems like no action can be taken on this issue until the bug is resolved in the registration code. I think he said that conversation had started, but I don't see any issues on the ANTs or ANTsPy repos.

**Comment by dyf** [comment]
@sharmishtaa @camilolaiton extra nice requirement @miketaormina  just mentioned is to save the reverse transform in such a way that we can generate neuroglancer visualizations in sample space on the fly.

**Comment by galenlynch** [comment]
+1 to this. It's very useful to go in both directions

**Comment by galenlynch** [comment]
My understanding is that the forward transform maps the CCF to the light sheet data (in this case), which shares an affine transform with the inverse transform. I would like to map the CCF into the light sheet space to quantify how well the brain was aligned to the CCF. I also think it's useful to be able to visualize the CCF in the light sheet space.

**Comment by galenlynch** [comment]
@miketaormina I don't understand this "bug" in ants that you mentioned. Here the transform is from the CCF to light sheet, so the inverse nonlinear warp puts the light sheet in CCF space. Both have the same affine transform. When you apply the forward transform (ccf -> light sheet) it does seem to put the CCF in light sheet space.

**Comment by miketaormina** [comment]
@galenlynch I don't know if it was a bug or not, but my understanding is that this is resolved. The non-affine part is the thing that needs to be stored as two separate operators, since it's not an invert-able operator. Both are computed by the algorithm, it's just that both also need to be stored in order to do both transforms.
